version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=54320
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ssmsbe
      - PORT=5000
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '54320:5432'

volumes:
  db:
    driver: local
